# =========================================
# Tri-plane 2.5D QSM — Unified Config (v1.1)
# =========================================
seed: 2025
device: cuda            # or "cpu"
out_dir: checkpoints    # 训练输出目录（如跑 UKAN 想分开保存，可临时改为 "checkpoints_ukan"）

# ---------- Data ----------
data:
  train:
    vols:
      - /ABS/PATH/TO/train/vol_001.npy
      # - /ABS/PATH/TO/train/vol_002.npy
    masks:
      - /ABS/PATH/TO/train/mask_001.npy
    chis:
      - /ABS/PATH/TO/train/chi_001.npy
  val:
    vols:
      - /ABS/PATH/TO/val/vol_101.npy
    masks:
      - /ABS/PATH/TO/val/mask_101.npy
    chis:
      - /ABS/PATH/TO/val/chi_101.npy

# 2.5D tri-plane 切片与滑窗
l: 11                   # 每平面堆叠切片数（奇数；中心切片对齐）
patch: 96               # 立方补丁尺寸
stride: 64              # 滑窗步幅
normalize: zscore       # zscore|minmax|none

# Dataloader
num_workers: 4
pin_memory: true
cudnn_benchmark: true

# ---------- Optim / Sched ----------
epochs: 80
batch_size: 1
optimizer: adamw
lr: 2.0e-4
weight_decay: 1.0e-4
betas: [0.9, 0.999]
grad_clip: 0.0
amp: true               # 混合精度
save_every: 5           # 每 N 个 epoch 存一次

# ---------- Loss Weights ----------
loss:
  l1:        1.0
  grad_l1:   0.25
  hfen_log:  0.5
  ssim3d:    0.25
  rfft_l1:   0.25

# ---------- Tri-plane consistency（训练后半程，小权重） ----------
tri_consistency:
  enabled: true
  weight: 0.02
  mode: l1               # l1|cosine
  start_epoch: 40

# ---------- Slice-attention 温度（验证期可做 TTA-lite 扫描） ----------
tta_lite:
  enabled: true
  candidates: [0.8, 1.0, 1.2]

# ---------- Simple 分支（train.py 会读取到） ----------
simple:
  base: 64               # 基础通道数
  csar_rank: 4           # CSAR-Lite 低秩
  csar_T: 1.0            # 缺省温度（eval 可被 TTA-lite 覆盖）
  sem_hidden_ratio: 0.5  # 语义注意隐藏比例
  share_branch_weights: true

# ---------- UKAN 分支（train_ukan.py 会读取到） ----------
ukan:
  # 注意：UKAN 作为 2D 分支使用；输入为【单通道切片】→我们在包装层做 1→3 投影兼容 UKAN 默认的 in_chans=3
  in_chans: 3
  num_classes: 1         # 我们做回归（1 通道），包装层会在外侧接回 1 通道头
  embed_dims: [64, 128, 256, 512]   # 可按显存调小，如 [48,96,192,384]
  depths: [2, 2, 2, 2]
  drop_path_rate: 0.1
  # 其余 UKAN 内部超参采用官方默认；如 external 实现需要额外键，可在这里追加，不影响 Simple 训练

# ---------- Eval / Inference ----------
eval:
  tta: true               # 验证集做 TTA-lite（从 candidates 里挑最优）
  stitch: true            # 输出全体拼接指标
infer:
  amp: true
  batch: 1
